### ISSUE TITLE
Exporting props from ASC-UI

### ISSUE THREAD

**Issue by robinpiets** [Amsterdam/amsterdam-styled-components#1161]
In my project it would be really nice if I could import the props from ASC-UI components. This would make TypeScript projects that use ASC-UI much more efficient. 

Example (pseudo code):

``` js
import { Button, ButtonProps, ButtonVariantProps } from "@amsterdam/asc-ui";
// or import { Button, Props } from "@amstedam/asc-ui";

type NavProps = {
 buttonProps: ButtonProps;
 // or Props.Button
 buttonVariant: ButtonVariantProps;
 // or Props.ButtonVariant
 // ...
}

const Nav: React.FC<NavProps> = ({
 buttonProps,
 buttonVariant,
}) => {
 // ...
 return (
  <Button variant={buttonVariant} {...buttonProps} />
 )
}

```

**Comment by jonkoops** [comment]
Agreed this is something I would like to see as well. It would also mean that we need to have more specific names like `NavProps` instead of just `Props` for the interfaces.

This behaviour has already been requested in our [Conventional Exports RFC] (https://github.com/Amsterdam/amsterdam-styled-components/issues/260) so I am closing this as a duplicate.
