### ISSUE TITLE
Spacing for all components should follow a 4-point grid

### ISSUE THREAD

**Issue by royderks** [Amsterdam/amsterdam-styled-components#197]
**Describe the bug**
Spacing for all components should follow a 4-point grid, meaning i.e. `padding: 15px` is incorrect. 

**Expected behavior**
We expect all components to follow a 4-point grid. For the scenario above this means the padding is described like `padding: ${themeSpacing(3)};` or `padding: ${themeSpacing(4)};` depending on the designers preference.

**Additional context**
Check with the designers what their preferences are on a component basis

**Comment by jonkoops** [comment]
I think we can have a chat with the people behind the design system. I've asked Iris if she can include us in one of the upcoming meetings they have scheduled.

**Comment by royderks** [comment]
> I think we can have a chat with the people behind the design system. I've asked Iris if she can include us in one of the upcoming meetings they have scheduled.

@chrisvanmook has a meeting with one of them this week, maybe you can join?

**Comment by RCNEW** [comment]
Also, (as one of the people behind the design system) I can say in advance:  it is already clear that the 'redesign' of the design system will include a 4px grid in stead of the 5px grid it follows now.
So you are on the right track here.

But since the redesign will probably won't happen any time soon, the designs in the design system will continue to prescribe 5px spacing for now.

That said:  it would be ideal if, like @royderks suggests, there would be some kind of variable in your components library (like themeSpacing) to account for these deviations. That way you would be able to continue working on the 4px grid, while we can include your components in our 5px grid in the design system. Plus front-enders will have the ability to switch grids.

**Comment by jonkoops** [comment]
@RCNEW Since we do not have the time and resources to do this all at once, our proposal would be to introduce these changes gradually.

This means that when we align our components with the design system we will also propose to change the theme spacing used in the design for that specific component so that both our implementation and the reference design are aligned.

I'll keep this issue open for now so we can use it for tracking these changes.

**Comment by jonkoops** [comment]
We're going to discuss this during the next Design System meeting to find a resolution

**Comment by jonkoops** [comment]
After some discussion we have agreed to keep using a 4 point grid here in Amsterdam Styled Components. In the design system the 5 point grid will be used, and at some point it will be replaced with a 4 point grid.
