### ISSUE TITLE
In asc-assests the svg object is not available in v0.18.2

### ISSUE THREAD

**Issue by aditudorache** [Amsterdam/amsterdam-styled-components#334]
**Describe the bug**
Breaking change in `v0.18.2`

The functionality that was introduced in `v0.11.0` doesn't work anymore, the svg object is gone
`Added: new way of loading svg's: instead of importing like this: import Logo from '@datapunt/asc-assets/lib/assets/Icons/Logo.svg' you now can use the svg object: import { svg } from '@datapunt/asc-assets' and load it like this: background-image: url(${svg.Logo})`

**Comment by chrisvanmook** [comment]
@aditudorache Could you give a code example? Together with the version you're currently using (alpha?) thanks!

**Comment by aditudorache** [comment]
- checkout https://github.com/Amsterdam/signals-frontend
- update @datapunt/asc-ui to 0.18.2
- npm run build
- you get an error about an missing svg

**Comment by chrisvanmook** [comment]
In case you want to use it as a React component (that renders the svg in the DOM), just simply use
`import {Alert } from '@datapunt/asc-assets'`
If you need the svg itself (url, base64 etc..) make sure your webpack settings can handle svg's. You should import them using 
`import Logo from @datapunt/asc-assets/static/icons/Logo.svg` instead of `@datapunt/asc-assets/lib/assets/Icons/Logo.svg` (as stated in the Changelog)

Tell me if this solves your problem!

**Comment by chrisvanmook** [comment]
Figured out: https://github.com/Amsterdam/signals-frontend was using both babel-inline-react-svg and webpack's svg loader, causing issues.
