### ISSUE TITLE
Document themeColor and themeSpacing utilities

### ISSUE THREAD

**Issue by jonkoops** [Amsterdam/amsterdam-styled-components#641]
We currently don't have a lot of documentation for these methods. Having some example stories and documentation would be a great for people starting out with ASC.

**Comment by chrisvanmook** [comment]
Fixed in https://github.com/Amsterdam/amsterdam-styled-components/pull/715

https://amsterdam.github.io/amsterdam-styled-components/?path=/docs/utils-breakpoint--min-with-laptop-m
https://amsterdam.github.io/amsterdam-styled-components/?path=/docs/utils-themecolor--primary-colors
https://amsterdam.github.io/amsterdam-styled-components/?path=/docs/utils-themespacing--default-story
